### ISSUE TITLE
What does `show jobs` actually do?

### ISSUE THREAD

**Issue by chernals** [htcondor/vscode-htcondor#1]
Not clear if the extension is or should be working at the moment. Does `show job` run `condor_q` in a way? I can't get it work and show the list of running/pending jobs.

**Comment by maxhartke** [comment]
Are you able to use the `show job` command and just nothing is returned or are you unable to use it? In order to use it you need to be remoted connected to an access point. `show job` does not user `condor_q`. It stands up a flask API that uses the python bindings to get job data.

**Comment by maxhartke** [comment]
Ignore the above comment, I believe this is a bug I will look into ASAP and will update here once fixed.

**Comment by maxhartke** [comment]
As of version `1.3.0` the issue should be fixed and the command `show jobs` is working.

**Comment by chernals** [comment]
It works, thanks a lot !
